### ISSUE TITLE
`bundler` compatibility issues

### ISSUE THREAD

**Issue by viswavi** [aidewoode/jekyll-theme-mint#2]
When I try the `bundle` command on this package, I'm getting an error:
```
(base) vijay@Vijays-MBP-2:~/Documents/personal/website/jekyll-theme-mint$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.16)

  Current Bundler version:
    bundler (2.1.4)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.16)' in any of the relevant sources:
  the local ruby installation
```

**Comment by aidewoode** [comment]
That's because you use newer bundler to install dependencies. You can install older bundler to avoid this.  But I don't recommend it.  If you want to develop this theme, I recommend you use docker to setup dev environment. https://github.com/aidewoode/jekyll-theme-mint#development

If you just want to use this theme on your Jekyll site, you don't need to fork this repo and set up  dev environment on local. the recommended way is to use Jekyll to create new project, then add this theme to the Gemfile to use it. For more detail  you can view on Jekyll document. https://jekyllrb.com/docs/themes/
